version: '3.1'
services:
  testlink:
    build: .
    container_name: testlink
    ports:
      - '7777:8080'
      - '443:443'
    depends_on:
      - mysql_testlink
    volumes:
      - './gui/templates_c:/var/www/html/gui/templates_c'
      - './logs:/var/testlink/logs'
      - './upload_area:/var/www/html/upload_area'
    environment:
      - 'IMAGE_NAME=dice_testlink'
      - 'VOLUME_DIR_TESTLINK=./volume_testlink'
  mysql_testlink:
    image: 'mysql:5.7'
    ports:
      - '3301:3306'
    volumes:
      - './volume_mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=${mysql_root_password}
      - 'VOLUME_DIR_MYSQL=./volume_mysql'
